### ISSUE TITLE
Omar Hassan

### ISSUE THREAD

**Issue by hassanoe** [tpyork/hgen-612#11]
There was an issue with `reprex()` for the copied code; (this is related to running on Linux OS). To resolve it, i followed the answer from [this Stackoverflow question](https://stackoverflow.com/questions/64380485/reprex-error-on-linux-no-input-provided-and-clipboard-is-not-available)

reprex::reprex({    paste coded here  })  and selected to copy the output file manually 

``` r
n <- 10
mydat <- data.frame(exam_1 = rnorm(n, 70, 15),
                    exam_2 = rnorm(n, 86, 5),
                    exam_3 = rnorm(n, 68, 13)
)

mydat$lowest_exam = apply(mydat, 2, min)
#> Error in `$<-.data.frame`(`*tmp*`, lowest_exam, value = c(exam_1 = 42.6586616011486, : replacement has 3 rows, data has 10
```

<sup>Created on 2021-03-26 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by tpyork** [comment]
nice !
